### ISSUE TITLE
Change storagemount type to attachesTo

### ISSUE THREAD

**Issue by Well5a** [UST-DeMAF/kubernetes-mps-plugin#20]
Change in Kubernetes Plugin and Visualization Service.

use the location property for the mount path?

Definition in Tosca spec:
```
tosca.relationships.AttachesTo:
  derived_from: [tosca.relationships.Root](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#DEFN_TYPE_RELATIONSHIPS_ROOT)
  valid_target_types: [ [tosca.capabilities.Attachment](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#DEFN_TYPE_CAPABILITIES_ATTACHMENT) ]
  properties:
    location:
      type: string
      constraints:
        - min_length: 1
    device:
      type: string
      required: false
```
